version: 0.1

services:
  bnb-tcp:
    image: tsanee9/bnb-tcp:latest
    imagePullPolicy: Always

    ports:
      - containerPort: 80
        protocol: TCP
        expose: true

    # Configuration is handled through the frontend UI at runtime
    # No environment variables required - users configure API keys in-app
    env:
      - name: NODE_ENV
        value: production

    resourceUsage:
      idle:
        cpu: 500
        memory: 512
