version: 0.1

services:
  bnb-tcp:
    image: tsanee9/bnb-tcp:v4
    imagePullPolicy: Always

    ports:
      - containerPort: 80
        protocol: TCP
        expose: true

    # Environment variables are no longer needed at runtime
    # as they are embedded during Docker build process
    env:
      - name: NODE_ENV
        value: production

    resourceUsage:
      idle:
        cpu: 500
        memory: 512
      active:
        cpu: 1000
        memory: 1024
